from .thresholds import (
    EVENT_COOLDOWN_FRAMES,
    PASS_DISTANCE_THRESHOLD,
    SHOT_HOOP_DOT_MIN,
    SHOT_UPWARD_VELOCITY_THRESHOLD,
)

__all__ = [
    "EVENT_COOLDOWN_FRAMES",
    "PASS_DISTANCE_THRESHOLD",
    "SHOT_HOOP_DOT_MIN",
    "SHOT_UPWARD_VELOCITY_THRESHOLD",
]
